[project]
name = "client_onedoc"
version = "0.0.15"
authors = [
  { name="Pierre Dorge", email="pierre.dorge@onedoclabs.com" },
  { name="Titouan Launay", email="titouan.launay@onedoclabs.com" },
]
description = "Onedoc SDK for Python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "requests >= 2.0",
  "pikepdf >= 8.13.0"
]

[project.urls]
Homepage = "https://github.com/onedoclabs/onedoc"
Issues = "https://github.com/OnedocLabs/onedoc/issues"
